version: "3.7"

services:
  php:
    image: php
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/src/app
      - ./bootstrap:/src/bootstrap
      - ./config:/src/config
      - ./database:/src/database
      - ./public:/src/public
      - ./resources:/src/resources
      - ./routes:/src/routes
      - ./storage:/src/storage
      - ./tests:/src/tests
      - ./artisan:/src/artisan
      - ./composer.json:/src/composer.json
      - ./composer.lock:/src/composer.lock
      - ./package.json:/src/package.json
      - ./phpunit.xml:/src/phpunit.xml
      - ./server.php:/src/server.php
      - ./webpack.mix.js:/src/webpack.mix.js
  web:
    image: nginx:latest
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./public:/src/public
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: 'test@test.com'
      PGADMIN_DEFAULT_PASSWORD: 'secret'
  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    volumes:
      - ./public:/src/public
      - ./resources:/src/resources
      - ./package.json:/src/package.json
      - ./package-lock.json:/src/package-lock.json
      - ./webpack.mix.js:/src/webpack.mix.js
